{{- if and .Values.secretMounts.auth.create (not .Values.secretMounts.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shakti.authSecretName" . }}
  labels:
    {{- include "shakti.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secretMounts.auth.key }}: |-
{{ .Values.secretMounts.auth.sharedSecretsJson | nindent 4 }}
{{- end }}
