{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shakti.postgresSecretName" . }}
  labels:
    {{- include "shakti.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgres.auth.passwordKey }}: {{ .Values.postgres.auth.password | quote }}
{{- end }}
